name: CI Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
        
    - name: Run build validation
      run: npm run build
      
    - name: Validate extension structure
      run: |
        echo "Validating extension structure..."
        
        # Check required files exist
        required_files=(
          "manifest.json"
          "src/background/background.js"
          "src/content/content.js"
          "src/popup/popup.html"
          "src/options/options.html"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Error: Required file $file not found"
            exit 1
          else
            echo "✓ $file"
          fi
        done
        
        # Check manifest.json validity
        if ! jq empty manifest.json 2>/dev/null; then
          echo "Error: manifest.json is not valid JSON"
          exit 1
        else
          echo "✓ manifest.json is valid JSON"
        fi
        
        # Check version consistency
        manifest_version=$(jq -r '.version' manifest.json)
        package_version=$(jq -r '.version' package.json)
        
        if [ "$manifest_version" != "$package_version" ]; then
          echo "Warning: Version mismatch between manifest.json ($manifest_version) and package.json ($package_version)"
        else
          echo "✓ Version consistency: $manifest_version"
        fi

    - name: Validate icon files
      run: |
        echo "Validating icon files..."

        # Check required icon files exist
        required_icons=(
          "assets/icons/icon16.png"
          "assets/icons/icon32.png"
          "assets/icons/icon48.png"
          "assets/icons/icon128.png"
        )

        for icon in "${required_icons[@]}"; do
          if [ ! -f "$icon" ]; then
            echo "Error: Required icon file $icon not found"
            exit 1
          else
            echo "✓ $icon"
          fi
        done

    - name: Create test package
      run: |
        mkdir -p test-package
        cp manifest.json test-package/
        cp -r src test-package/
        cp -r assets test-package/

        # Copy required node_modules dependencies
        mkdir -p test-package/node_modules/@mozilla/readability
        cp node_modules/@mozilla/readability/Readability.js test-package/node_modules/@mozilla/readability/
        cp node_modules/@mozilla/readability/Readability-readerable.js test-package/node_modules/@mozilla/readability/

        echo "Test package created successfully"
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-build
        path: test-package/
        retention-days: 7
