name: Build and Release CRX

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
        
    - name: Run build validation
      run: npm run build
      
    - name: Validate icon files
      run: |
        echo "Validating required icon files..."

        # Check required icon files exist
        required_icons=(
          "assets/icons/icon16.png"
          "assets/icons/icon32.png"
          "assets/icons/icon48.png"
          "assets/icons/icon128.png"
        )

        for icon in "${required_icons[@]}"; do
          if [ ! -f "$icon" ]; then
            echo "Error: Required icon file $icon not found"
            exit 1
          else
            echo "✓ $icon exists"
          fi
        done

    - name: Create extension package
      run: |
        # Use the existing package script for consistency
        npm run package:zip

        # Verify _locales directory exists in the package
        if [ ! -d "dist/extension/_locales" ]; then
          echo "Error: _locales directory missing from package"
          exit 1
        fi

        # Verify required locale files exist
        if [ ! -f "dist/extension/_locales/en/messages.json" ]; then
          echo "Error: English locale file missing"
          exit 1
        fi

        # Verify Readability.js files exist in the package
        if [ ! -f "dist/extension/vendor/readability/Readability.js" ]; then
          echo "Error: Readability.js missing from package"
          exit 1
        fi

        echo "Extension package created and verified in dist/extension"
        
    - name: Install Chrome for CRX packaging
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Generate private key for CRX
      run: |
        # Generate a private key for signing the CRX
        openssl genrsa -out extension.pem 2048
        echo "Generated private key for CRX signing"
        
    - name: Package CRX
      run: |
        # Verify extension structure before packaging
        echo "Verifying extension structure..."
        ls -la dist/extension/
        ls -la dist/extension/_locales/

        # Create CRX package using Chrome
        google-chrome --headless --disable-gpu --pack-extension=dist/extension --pack-extension-key=extension.pem

        # Verify CRX was created
        if [ ! -f "dist/extension.crx" ]; then
          echo "Error: CRX file was not generated"
          exit 1
        fi

        # Move the generated CRX to a predictable location
        mv dist/extension.crx open-translate-${GITHUB_REF#refs/tags/}.crx

        echo "CRX package created: open-translate-${GITHUB_REF#refs/tags/}.crx"
        
    - name: Verify ZIP package
      run: |
        # ZIP was already created by npm run package:zip, just rename it
        if [ -f "dist/open-translate-v*.zip" ]; then
          mv dist/open-translate-v*.zip open-translate-${GITHUB_REF#refs/tags/}.zip
        else
          echo "Error: ZIP package not found"
          exit 1
        fi
        echo "ZIP package verified: open-translate-${GITHUB_REF#refs/tags/}.zip"
        
    - name: Generate release notes
      run: |
        echo "# Open Translate ${GITHUB_REF#refs/tags/}" > release-notes.md
        echo "" >> release-notes.md
        echo "## 安装说明" >> release-notes.md
        echo "" >> release-notes.md
        echo "### 方式一：直接安装 CRX 文件" >> release-notes.md
        echo "1. 下载 \`open-translate-${GITHUB_REF#refs/tags/}.crx\` 文件" >> release-notes.md
        echo "2. 打开 Chrome 浏览器，进入 \`chrome://extensions/\`" >> release-notes.md
        echo "3. 启用右上角的「开发者模式」" >> release-notes.md
        echo "4. 将 CRX 文件拖拽到扩展页面进行安装" >> release-notes.md
        echo "" >> release-notes.md
        echo "### 方式二：解压安装" >> release-notes.md
        echo "1. 下载 \`open-translate-${GITHUB_REF#refs/tags/}.zip\` 文件并解压" >> release-notes.md
        echo "2. 打开 Chrome 浏览器，进入 \`chrome://extensions/\`" >> release-notes.md
        echo "3. 启用右上角的「开发者模式」" >> release-notes.md
        echo "4. 点击「加载已解压的扩展程序」" >> release-notes.md
        echo "5. 选择解压后的文件夹" >> release-notes.md
        echo "" >> release-notes.md
        echo "## 配置说明" >> release-notes.md
        echo "安装后请参考项目文档配置 API 设置。" >> release-notes.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          open-translate-*.zip
          open-translate-*.crx
        body_path: release-notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-packages
        path: |
          open-translate-*.zip
          open-translate-*.crx
          dist/extension/**
        retention-days: 30
